### ISSUE TITLE
Control Task Switching to avoid I2C data corruption

### ISSUE THREAD

**Issue by dhamukrish** [greiman/ChNil#4]
I have two I2C devices which are handled in two different threads. After sometime (randomly), my I2C LCD display show all junk chars followed that system hung. Then, have to forcefully reset the Arduino Uno R3. 

Please note that this wasn't happened when only one I2C device was added (RTC) in my project. Later, have added I2C LCD as second one.

Could you please help how corruption can be avoided and control task switching

**Comment by greiman** [comment]
Use a semaphore to control access to the I2C controller.
